// findq_parser.bison.y

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// c++ parser skeleton file
%skeleton "lalr1.cc"

// minimum bison version 3.8
%require "3.8"

%language "c++"

// generate parser description report .output file
%verbose

// names of generated parser files
%defines "findq_parser.bison.h"
%output "findq_parser.bison.cpp"

// enable debug trace
%define parse.trace

// add location parameter to symbol constructor
%locations

// generate header for location to be used outside of bison parser
%define api.location.file "locations.bison.h"

%define parse.error custom

// want to return character token from flex but don't think it can work with api.token.constructor
// better lookup performance at cost of disallowing literal characters in grammar
%define api.token.raw

%code requires {
// %code requires codeblock goes at top of .h outside of namespace and parser class
// your license for .h file, standard c++ #includes and defines

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <string>
#include <vector>
#include <functional>
#include <chrono>
#include <variant>
#include <optional>
#include <print>

#include "locations.bison.h"

#include "ast/findq_token_types.h"
#include "ast/findq_ast.h"

#ifdef _MSC_VER
// disable vc++ warning C4065, switch statement contains default but no case labels in code generated for basic_symbol::clear() in .h file
#pragma warning(push)
#pragma warning(disable: 4065)
#endif

namespace findqparser {
using namespace std;
using namespace chrono;

#if 0
struct NumberArg {
  int sign = 0;
  uint64_t val;
  auto operator<=>(const NumberArg&) const = default;
};
#endif

struct RuleCallbacks {
  optional<function<void(void)>> binary_expression_from_and_cb{};
  optional<function<void(void)>> and_expression_from_list_cb{};
  optional<function<void(void)>> unary_expression_from_not_cb{};
  optional<function<void(const string&)>> string_arg_cb{};
};

struct BisonParam {
  FindqAstNode ast;

  RuleCallbacks ruleCb;
  struct Stats {
    time_point<steady_clock> parseStartTime;
    time_point<steady_clock> parseEndTime;
    duration<double> parseTimeSec;
  } stats;
};

// info for lexer to use in yylex
struct LexParam {
// position in input stream for lexer to update
  location loc{};
};

#if 0
OptionsMap curPositionalOptions = defaultPositionalOptions;
#endif

}

// println formatter for location object
template<>
struct std::formatter<findqparser::location> {
  std::format_context::iterator format(const findqparser::location& loc, std::format_context& ctx) const {
    std::ostringstream os;
    os << loc;
    return std::format_to(ctx.out(), "{}", os.str());
  }

  constexpr std::format_parse_context::const_iterator parse(std::format_parse_context& ctx) const {
    return ctx.begin();
  }
};


}

// namespace for parser generated by bison
%define api.namespace {findqparser}

// name of generated parser class
%define api.parser.class {FindqParser}

// parser constructor parameter 1
// this is the yylex bison will call, it can have any signature we want since it's a lambda passed in by the client that wraps and hides the actual yylex call
%parse-param {function<FindqParser::symbol_type(LexParam&)> yylex}

// parser constructor parameter 2
%parse-param {BisonParam& bisonParam}

// parser constructor parameter 3
// only because each lex-param also must be parse-param
%parse-param {LexParam& lexParam}

// yylex parameter 1
// pass location and lexical feedback info to lexer
%lex-param {LexParam& lexParam}

// use c++ classes as semantic types
%define api.value.type variant

// use c++ objects, changes signature of yylex, yylex now returns PGNParser::symbol_type, yylex takes no parameters, change everywhere yylex is referenced, eg parse-param, any lambdas
%define api.token.constructor

// enable c++ assert via internal YY_ASSERT to validate symbol use
%define parse.assert

%code provides {
// %code provides codeblock
// goes in .h after namespace and parser class
// everything here needs FindqParser defined earlier

#ifdef _MSC_VER
#pragma warning(pop)
#endif

// parser objects
namespace findqparser {

using namespace std;

}

}

%code top {
// % code top
// appears as topmost code block in generated .cpp file just below gnu license
// your license for .cpp file
/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

}

%{
// %{ unnamed codeblock
// goes at top of .cpp file after %code top, before namespace and parser class

%}

%code {
// %code
// appears in generated .cpp file after #include of generated .h file and before parser namespace and class

#include <string>
#include <chrono>

#include "ast/findq_ast.h"

#ifdef _MSC_VER
// disable vc++ warning C4065, switch statement contains default but no other case labels when there are no semantic actions
#pragma warning(push)
#pragma warning(disable: 4065)

// disable vc++ warning C4244, return conversion from const short to findqparser::FindqParser::state_type, possible loss of data
#pragma warning(push)
#pragma warning(disable: 4244)
#endif

using namespace std;
using findqparser::FindqParser;

namespace {
  const auto defaultInputName = "inputstream"s;
}

void FindqParser::error(const location& loc, const string& msg) {
  println("error at {}: {}", loc, msg);
}

// needed for %define parse.error custom
void FindqParser::report_syntax_error(const FindqParser::context& ctx) const {
  auto n = ctx.expected_tokens(NULL, 0);
  vector<FindqParser::symbol_kind_type> expectedTokens(n);
  ctx.expected_tokens(expectedTokens.data(), n);
  string expectedTokensList;
  for(auto i = 0; i < n - 1; ++i) {
    expectedTokensList += string(FindqParser::symbol_name(expectedTokens[i])) + ", ";
  }
  expectedTokensList += FindqParser::symbol_name(expectedTokens[n - 1]);
  stringstream loc;
  loc << ctx.location();
  print(stderr, "FindqParser.report_syntax_error: location \"{}\" token \"{}\" lookahead \"{}\" expected tokens \"{}\" \n", loc.str(), FindqParser::symbol_name(ctx.token()), ctx.lookahead().name(), expectedTokensList);
}

}

%initial-action {
// %initial-action codeblock
// goes inside parse() function in .cpp, it's a separate brace-scoped block, anything declared here is local to this block and cannot be used anywhere else in parse()

// suppress unused variable warning till fix in release after version 3.8.2, https://github.com/akimd/bison/commit/a166d5450e3f47587b98f6005f9f5627dbe21a5b
// yynerrs_ is local to generated parse function
  (void)yynerrs_;

  bisonParam.stats.parseStartTime = steady_clock::now();

  auto& loc = lexParam.loc;

  if(loc.begin.filename == nullptr) {
    loc.initialize(&defaultInputName);
  }
}

// token definitions

// find command
%token                           FIND                     "find"

// find primaries

// tests
%token                           AMIN                     "-amin"
%token                           ANEWER                   "-anewer"
%token                           ATIME                    "-atime"
%token                           CMIN                     "-cmin"
%token                           CNEWER                   "-cnewer"
%token                           CTIME                    "-ctime"
%token                           EMPTY                    "-empty"
%token                           EXECUTABLE               "-executable"
%token                           FALSE                    "-false"
%token                           FSTYPE                   "-fstype"
%token                           GID                      "-gid"
%token                           GROUP                    "-group"
%token                           ILNAME                   "-ilname"
%token                           INAME                    "-iname"
%token                           INUM                     "-inum"
%token                           IPATH                    "-ipath"
%token                           IREGEX                   "-iregex"
%token                           IWHOLENAME               "-iwholename"
%token                           LINKS                    "-links"
%token                           LNAME                    "-lname"
%token                           MMIN                     "-mmin"
%token                           MTIME                    "-mtime"
%token                           NAME                     "-name"
%token                           NEWER                    "-newer"
%token                           NEWERXY                  "-newerXY"
%token                           NOGROUP                  "-nogroup"
%token                           NOUSER                   "-nouser"
%token                           PATH                     "-path"
%token                           PERM                     "-perm"
%token                           READABLE                 "-readable"
%token                           REGEX                    "-regex"
%token                           SAMEFILE                 "-samefile"
%token                           SIZE                     "-size"
%token                           TRUE                     "-true"
%token                           TYPE                     "-type"
%token                           UID                      "-uid"
%token                           USED                     "-used"
%token                           USER                     "-user"
%token                           WHOLENAME                "-wholename"
%token                           WRITABLE                 "-writable"
%token                           XTYPE                    "-xtype"

// actions
%token                           DELETE                   "-delete"
%token                           EXEC                     "-exec"
%token                           EXECDIR                  "-execdir"
%token                           FLS                      "-fls"
%token                           FPRINT                   "-fprint"
%token                           FPRINT0                  "-fprint0"
%token                           FPRINTF                  "-fprintf"
%token                           LS                       "-ls"
%token                           OK                       "-ok"
%token                           OKDIR                    "-okdir"
%token                           PRINT                    "-print"
%token                           PRINT0                   "-print0"
%token                           PRINTF                   "-printf"
%token                           PRUNE                    "-prune"
%token                           QUIT                     "-quit"

// global options
%token                           DEPTH                    "-depth"
%token                           FILES0_FROM              "-files0-from"
%token                           HELP                     "-help"
%token                           IGNORE_READDIR_RACE      "-ignore_readdir_race"
%token                           MAXDEPTH                 "-maxdepth"
%token                           MINDEPTH                 "-mindepth"
%token                           MOUNT                    "-mount"
%token                           NOIGNORE_READDIR_RACE    "-noignore_readdir_race"
%token                           NOLEAF                   "-noleaf"
%token                           XDEV                     "-xdev"

// positional options
%token                           DAYSTART                 "-daystart"
%token                           FOLLOW                   "-follow"
%token                           NOWARN                   "-nowarn"
%token                           REGEXTYPE                "-regextype"
%token                           WARN                     "-warn"

// operators
%token                           NOT                      "!"
%token                           AND                      "-a"
%token                           OR                       "-o"
%token                           COMMA                    ","
%token                           LEFT_PAREN               "("
%token                           RIGHT_PAREN              ")"

%token                           SEMICOLON                ";"

// tokens with values

%token <NumberArg>               NUMBER_ARG
%token <string>                  STRING_ARG
%token <vector<string>>          EXEC_ARG

%token <string>                  START_POINT

// we choose to skip TestPrimary, ActionPrimary types for efficiency
%nterm <Primary>                 primary
%nterm <Primary>                 test
%nterm <Primary>                 action
%nterm <Primary>                 global_opt
%nterm <Primary>                 positional_opt

%nterm <Unit>                    unit
%nterm <Term>                    term
%nterm <AndExpr>                 and_expr
%nterm <OrExpr>                  or_expr
%nterm <CommaExpr>               comma_expr
%nterm <Cmd>                     cmd
%nterm <vector<Cmd>>             cmds
%nterm <Findq>                   findq



// the start or root symbol of grammar
%start findq

%%
// no code allowed in rules section outside of actions
// these are bison comments that do not appear in generated .cpp file

findq: cmds {
  $$.cmds = move($cmds);
}

cmds:
  cmd {
  $$.push_back(move($cmd));
}
| cmds cmd {
  $$ = move($1);
  $$.push_back(move($cmd));
}

cmd:
 "find" comma_expr {
  $$.expr = move($comma_expr);
}
| "find" start_points comma_expr {
  $$.expr = move($comma_expr);
}

comma_expr:
  or_expr {
  $$.segs.push_back(move($or_expr));
}
| comma_expr "," or_expr {
  $$ = move($1);
  $$.segs.push_back(move($or_expr));
}

or_expr:
  and_expr {
  $$.ors.push_back(move($and_expr));
}
| or_expr "-o" and_expr {
  $$ = move($1);
  $$.ors.push_back(move($and_expr));
}

and_expr:
  term {
  $$.ands.push_back(move($term));

}
| and_expr and_op term {
  $$ = move($1);
  $$.ands.push_back(move($term));
}

term:
  unit {
  $$.unit = move($unit);
}
| "!" unit {
  $$.unit = move($unit);
  $$.isTrue = false;
}

unit:
  primary {
  $$ = move($1);
}
| group {
}

group: "(" comma_expr ")"

primary:
  test { $$ = move($1); }
| action { $$ = move($1); }
| global_opt { $$ = move($1); }
| positional_opt { $$ = move($1); }

and_op: %empty | "-a"

start_points: START_POINT | start_points START_POINT

test:
  "-amin"                      NUMBER_ARG {
  $$ = Amin{move($2)};
}
| "-anewer"                    STRING_ARG {
  $$ = Anewer{move($2)};
}
| "-atime"                     NUMBER_ARG {
  $$ = Atime{move($2)};
}
| "-cmin"                      NUMBER_ARG {
  $$ = Cmin{move($2)};
}
| "-cnewer"                    STRING_ARG {
  $$ = Cnewer{move($2)};
}
| "-ctime"                     NUMBER_ARG {
  $$ = Ctime{move($2)};
}
| "-empty" {
  $$ = Empty{};
}
| "-executable" {
  $$ = Executable{};
}
| "-false" {
  $$ = False{};
}
| "-fstype"                    STRING_ARG {
  $$ = Fstype{move($2)};
}
| "-gid"                       NUMBER_ARG {
  $$ = Gid{move($2)};
}
| "-group"                     STRING_ARG {
  $$ = Group{move($2)};
}
| "-ilname"                    STRING_ARG {
  $$ = Ilname{move($2)};
}
| "-iname"                     STRING_ARG {
  $$ = Iname{move($2)};
}
| "-inum"                      NUMBER_ARG {
  $$ = Inum{move($2)};
}
| "-ipath"                     STRING_ARG {
  $$ = Ipath{move($2)};
}
| "-iregex"                    STRING_ARG {
  $$ = Iregex{move($2)};
}
| "-iwholename"                STRING_ARG {
  $$ = Iwholename{move($2)};
}
| "-links"                     NUMBER_ARG {
  $$ = Links{move($2)};
}
| "-lname"                     STRING_ARG {
  $$ = Lname{move($2)};
}
| "-mmin"                      NUMBER_ARG {
  $$ = Mmin{move($2)};
}
| "-mtime"                     NUMBER_ARG {
  $$ = Mtime{move($2)};
}
| "-name"                      STRING_ARG {
  $$ = Name{move($2)};
}
| "-newer"                     STRING_ARG {
  $$ = Newer{move($2)};
}
| "-newerXY"                   STRING_ARG {
  $$ = NewerXY{move($2)};
}
| "-nogroup" {
  $$ = NoGroup{};
}
| "-nouser" {
  $$ = NoUser{};
}
| "-path"                      STRING_ARG {
  $$ = Path{move($2)};
}
| "-perm"                      STRING_ARG {
  $$ = Perm{move($2)};
}
| "-readable" {
  $$ = Readable{};
}
| "-regex"                     STRING_ARG {
  $$ = Regex{move($2)};
}
| "-samefile" {
  $$ = Samefile{};
}
| "-size"                      NUMBER_ARG {
  $$ = Size{move($2)};
}
| "-true" {
  $$ = True{};
}
| "-type"                      STRING_ARG {
  $$ = Type{move($2)};
}
| "-uid"                       NUMBER_ARG {
  $$ = Uid{move($2)};
}
| "-used"                      NUMBER_ARG {
  $$ = Used{move($2)};
}
| "-user"                      STRING_ARG {
  $$ = User{move($2)};
}
| "-wholename"                 STRING_ARG {
  $$ = Wholename{move($2)};
}
| "-writable" {
  $$ = Writable{};
}
| "-xtype"                     STRING_ARG {
  $$ = Xtype{move($2)};
}

action:
  "-delete" {}
| "-exec"                      EXEC_ARG {}
| "-execdir"                   EXEC_ARG {}
| "-fls"                       STRING_ARG {}
| "-fprint"                    STRING_ARG {}
| "-fprint0"                   STRING_ARG {}
| "-fprintf"                   STRING_ARG {}
| "-ls" {}
| "-ok"                        EXEC_ARG {}
| "-okdir"                     EXEC_ARG {}
| "-print" {}
| "-print0" {}
| "-printf"                    STRING_ARG {}
| "-prune" {}
| "-quit" {}

global_opt:
  "-depth" {}
| "-files0-from"               STRING_ARG {}
| "-help" {}
| "-ignore_readdir_race" {}
| "-maxdepth"                  NUMBER_ARG {}
| "-mindepth"                  NUMBER_ARG {}
| "-mount" {}
| "-noignore_readdir_race" {}
| "-noleaf" {}
| "-xdev" {}

positional_opt:
  "-daystart" {}
| "-follow" {}
| "-nowarn" {}
| "-regextype"                 STRING_ARG {}
| "-warn" {}





/*
findq: find_commands

find_commands: find_command | find_commands find_command

find_command: "find" binary_expression | "find" starting_points binary_expression

starting_points: STARTING_POINT | starting_points STARTING_POINT

binary_expression: and_expression {
  if(bisonParam.ruleCb.binary_expression_from_and_cb) {
    (*bisonParam.ruleCb.binary_expression_from_and_cb)();
  }
}
| or_expression | comma_expression

and_expression:
  unary_expression
| and_expression and_operator unary_expression {
  if(bisonParam.ruleCb.and_expression_from_list_cb) {
    (*bisonParam.ruleCb.and_expression_from_list_cb)();
  }
}

and_operator: %empty | "-and"

or_expression: binary_expression "-or" and_expression

comma_expression: binary_expression "," and_expression

unary_expression: primary | "-not" primary  {
  if(bisonParam.ruleCb.unary_expression_from_not_cb) {
    (*bisonParam.ruleCb.unary_expression_from_not_cb)();
  }
}
| group

group: "(" binary_expression ")"

primary: test | action | global_option | positional_option

test:
  "-amin"                      number_arg
| "-anewer"                    string_arg
| "-atime"                     number_arg
| "-cmin"                      number_arg
| "-cnewer"                    string_arg
| "-ctime"                     number_arg
| "-empty"
| "-executable"
| "-false"
| "-fstype"                    string_arg
| "-gid"                       number_arg
| "-group"                     string_arg
| "-ilname"                    string_arg
| "-iname"                     string_arg
| "-inum"                      number_arg
| "-ipath"                     string_arg
| "-iregex"                    string_arg
| "-iwholename"                string_arg
| "-links"                     number_arg
| "-lname"                     string_arg
| "-mmin"                      number_arg
| "-mtime"                     number_arg
| "-name"                      string_arg
| "-newer"                     string_arg
| "-newerXY"                   string_arg
| "-nogroup"
| "-nouser"
| "-path"                      string_arg
| "-perm"                      string_arg
| "-readable"
| "-regex"                     string_arg
| "-samefile"
| "-size"                      number_arg
| "-true"
| "-type"                      string_arg
| "-uid"                       number_arg
| "-used"                      number_arg
| "-user"                      string_arg
| "-wholename"                 string_arg
| "-writable"
| "-xtype"                     string_arg

action:
  "-delete"
| "-exec"                      exec_args
| "-execdir"                   exec_args
| "-fls"                       string_arg
| "-fprint"                    string_arg
| "-fprint0"                   string_arg
| "-fprintf"                   string_arg
| "-ls"
| "-ok"                        exec_args
| "-okdir"                     exec_args
| "-print"
| "-print0"
| "-printf"                    string_arg
| "-prune"
| "-quit"

global_option:
  "-depth"
| "-files0-from"               string_arg
| "-help"
| "-ignore_readdir_race"
| "-maxdepth"                  number_arg
| "-mindepth"                  number_arg
| "-mount"
| "-noignore_readdir_race"
| "-noleaf"
| "-xdev"

positional_option:
  "-daystart"
| "-follow"
| "-nowarn"
| "-regextype"                 string_arg
| "-warn"

string_arg: set_lexer_string_state "string"[string] unset_lexer_state {
  if(bisonParam.ruleCb.string_arg_cb) {
    (*bisonParam.ruleCb.string_arg_cb)($string);
  }
}

number_arg: set_lexer_number_state "number" unset_lexer_state

exec_args: set_lexer_exec_state strings ";" unset_lexer_state

strings: "string" | strings "string"

// midrule actions

set_lexer_string_state: %empty {
#if 0
  bisonParam.lexer.setState(Lexer::State::stringArg);
#endif
}

set_lexer_number_state: %empty {
#if 0
  bisonParam.lexer.setState(Lexer::State::numberArg);
#endif
}

set_lexer_exec_state: %empty {
#if 0
  bisonParam.lexer.setState(Lexer::State::execArgs);
#endif
}

unset_lexer_state: %empty {
#if 0
  bisonParam.lexer.unsetState();
#endif
}
*/

%%
// %code epilog block
// goes at bottom of generated .cpp file after namespace and parser implementation


#ifdef _MSC_VER
#pragma warning(pop)
#pragma warning(pop)
#endif

