#ifndef FINDQ_LEXER_METHODS_H
#define FINDQ_LEXER_METHODS_H
// findq_lexer_methods.h

/*
MIT License

Copyright (c) 2024-2026 Zartaj Majeed

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/*
file to #include in flex .l epilog because it needs symbols in .cpp file generated by flex
can be named .h or .cpp
*/

#include "lexer/findq_lexer.h"
#include "findq_parser.bison.h"

namespace findqparser {
using namespace std;

int Lexer::setState(const State state) {

  int newState;
  switch(state) {
    case State::stringArg:
      newState = SC_STRING_ARG_WHITESPACE;
      break;
    case State::numberArg:
      newState = SC_NUMBER_ARG_WHITESPACE;
      break;
    case State::execArgs:
      newState = SC_EXEC_ARGS_WHITESPACE;
      break;
    default:
      return -1;
  }

  auto oldState = yy_top_state();
  yy_push_state(newState);
  return oldState;
}

void Lexer::unsetState() {
  yy_pop_state();
}

}

#endif

